services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: devops_db
    ports:
      - "3306:3306"

  backend:
    image: anushak1005/backend-app
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  frontend:
    image: anushak1005/frontend-app
    container_name: frontend
    ports:
      - "3000:80"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend